### ISSUE TITLE
你好，最近做蓝牙项目用了你的框架，发现一处崩溃

### ISSUE THREAD

**Issue by ganjmeng** [chenliangloveyou/EasyBluetooth#2]
![image](https://user-images.githubusercontent.com/12026835/31574689-f9db0da4-b106-11e7-905c-27de90f8d474.png)
蓝牙连接过程中把硬件重启，就会崩溃在这。望大神解决

**Comment by chenliangloveyou** [comment]
您好，再试一下，问题解决了吗？ 如果还有问题，希望多多提出。

**Comment by ganjmeng** [comment]
谢谢，等下回去试试，你这个框架是我见过写的最好的蓝牙框架了

**Comment by ganjmeng** [comment]
![image](https://user-images.githubusercontent.com/12026835/31668518-0477323a-b385-11e7-8200-063dce1b193a.png)
大神，这个方法好像有些问题，按条件搜索回调的时候就提示连接设备了，其实没有调用连接的方法他自己就连接上了，用名字判断的没有问题
![image](https://user-images.githubusercontent.com/12026835/31668483-e8621fc4-b384-11e7-978f-077068973ba2.png)

**Comment by ganjmeng** [comment]
找到问题了，是我看错了，有两种方法一种是搜索，一种是搜索完自动连接。抱歉，我没看仔细，太高级了
